"""
Static reference inventory catalog for HNP-managed NetBox seeds.

# Repo-owned static inventory only. For ownership rules see fabric_profiles/README.md.

This covers repo-owned, deterministic inventory that should be recreated by
management commands after a local inventory purge/reset.
"""

NETWORK_TRANSCEIVER_PROFILE_SCHEMA = {
    "type": "object",
    "properties": {
        "medium": {
            "type": "string",
            "enum": ["MMF", "SMF", "DAC", "ACC"],
        },
        "standard": {"type": "string"},
        "cage_type": {
            "type": "string",
            "enum": [
                "QSFP112",
                "QSFP-DD",
                "QSFP28",
                "QSFP56",
                "SFP28",
                "OSFP",
                "SFP+",
                "RJ45",
            ],
        },
        "connector": {
            "type": "string",
            "enum": ["LC", "MPO-12", "MPO-16", "Dual MPO-12", "Direct"],
        },
        "lane_count": {"type": "integer", "minimum": 1},
        "reach_class": {
            "type": "string",
            "enum": ["SR", "LR", "DR", "FR", "ER", "ZR", "VR", "DAC"],
        },
        "wavelength_nm": {"type": "integer"},
        "gearbox_present": {"type": "boolean"},
        "breakout_topology": {"type": "string"},
        "cable_assembly_type": {
            "type": "string",
            "enum": ["none", "DAC", "ACC", "AOC"],
        },
        "far_end_medium": {
            "type": "string",
            "enum": ["MMF", "SMF", "DAC", "ACC", "Copper"],
        },
        "far_end_cage_type": {
            "type": "string",
            "enum": ["QSFP112", "QSFP-DD", "QSFP28", "QSFP56", "SFP28", "OSFP", "SFP+", "RJ45"],
        },
        "optical_lane_pattern": {
            "type": "string",
            "enum": [
                "SR",
                "SR2",
                "SR4",
                "SR8",
                "DR4",
                "DR8",
                "FR4",
                "VR4",
                "PSM4",
            ],
        },
        "host_serdes_gbps_per_lane": {"type": "integer", "minimum": 1},
    },
}


STATIC_TRANSCEIVER_MODULE_TYPES = [
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-A9220-VR",
        "part_number": "R4113-A9220-VR",
        "description": "800G OSFP112 2xVR4 (2xMPO12)",
        "comments": "Celestica qualified optic for DS5000/DS4101/DS4100.",
        "attribute_data": {
            "cage_type": "OSFP",
            "medium": "MMF",
            "connector": "Dual MPO-12",
            "wavelength_nm": 850,
            "standard": "800GBASE-2xVR4",
            "reach_class": "VR",
            "lane_count": 8,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "VR4",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "2x400g",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-A9310-SR",
        "part_number": "R4113-A9310-SR",
        "description": "800G OSFP112 SR8 (MPO-16)",
        "comments": "Celestica qualified optic for DS5000/DS4101/DS4100.",
        "attribute_data": {
            "cage_type": "OSFP",
            "medium": "MMF",
            "connector": "MPO-16",
            "wavelength_nm": 850,
            "standard": "800GBASE-SR8",
            "reach_class": "SR",
            "lane_count": 8,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "SR8",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-A9221-DR",
        "part_number": "R4113-A9221-DR",
        "description": "800G OSFP112 2xDR4 (2xMPO12)",
        "comments": "Celestica qualified optic for DS5000/DS4101/DS4100.",
        "attribute_data": {
            "cage_type": "OSFP",
            "medium": "SMF",
            "connector": "Dual MPO-12",
            "wavelength_nm": 1310,
            "standard": "800GBASE-2xDR4",
            "reach_class": "DR",
            "lane_count": 8,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "DR4",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "2x400g",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-75111-DR",
        "part_number": "R4113-75111-DR",
        "description": "100G QSFP28 DR1 100G QSFP28 Duplex LC 500m 1310 SMF",
        "comments": "Celestica qualified 100G DR1 optic for DS3000-side uplinks.",
        "attribute_data": {
            "cage_type": "QSFP28",
            "medium": "SMF",
            "connector": "Duplex LC",
            "wavelength_nm": 1310,
            "standard": "100GBASE-DR",
            "reach_class": "DR",
            "lane_count": 1,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "DR1",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-75210-SR",
        "part_number": "R4113-75210-SR",
        "description": "100G QSFP28 SR4",
        "comments": "Celestica qualified 100G SR4 optic for switch-side 100GbE server links.",
        "attribute_data": {
            "cage_type": "QSFP28",
            "medium": "MMF",
            "connector": "MPO-12",
            "wavelength_nm": 850,
            "standard": "100GBASE-SR4",
            "reach_class": "SR",
            "lane_count": 4,
            "host_serdes_gbps_per_lane": 25,
            "optical_lane_pattern": "SR4",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-75C41-03",
        "part_number": "R4113-75C41-03",
        "description": "100G QSFP28 to 4x25G SFP28 breakout DAC, 3m",
        "comments": "Celestica 100G -> 4x25G breakout DAC for switch-side 25GbE border fanout.",
        "attribute_data": {
            "cage_type": "QSFP28",
            "medium": "DAC",
            "connector": "Direct",
            "standard": "100GBASE-CR4",
            "reach_class": "DAC",
            "lane_count": 4,
            "host_serdes_gbps_per_lane": 25,
            "optical_lane_pattern": None,
            "gearbox_present": False,
            "cable_assembly_type": "DAC",
            "breakout_topology": "4x25g",
            "far_end_medium": "MMF",
            "far_end_cage_type": "SFP28",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-A9311-DR",
        "part_number": "R4113-A9311-DR",
        "description": "800G OSFP112 DR8 (MPO-16)",
        "comments": "Celestica qualified optic for DS5000/DS4101/DS4100.",
        "attribute_data": {
            "cage_type": "OSFP",
            "medium": "SMF",
            "connector": "MPO-16",
            "wavelength_nm": 1310,
            "standard": "800GBASE-DR8",
            "reach_class": "DR",
            "lane_count": 8,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "DR8",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-A9121-FR",
        "part_number": "R4113-A9121-FR",
        "description": "800G OSFP112 2xFR4 (LC)",
        "comments": "Celestica qualified optic for DS5000/DS4101/DS4100.",
        "attribute_data": {
            "cage_type": "OSFP",
            "medium": "SMF",
            "connector": "LC",
            "standard": "800GBASE-2xFR4",
            "reach_class": "FR",
            "lane_count": 8,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "FR4",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "2x400g",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-98210-BI",
        "part_number": "R4113-98210-BI",
        "description": "400G QSFP-DD SR4.2 BiDi",
        "comments": "Celestica qualified optic for DS4000/DS4001.",
        "attribute_data": {
            "cage_type": "QSFP-DD",
            "medium": "MMF",
            "connector": "LC",
            "wavelength_nm": 850,
            "standard": "400GBASE-SR4.2",
            "reach_class": "SR",
            "lane_count": 4,
            "host_serdes_gbps_per_lane": 100,
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-98210-SR",
        "part_number": "R4113-98210-SR",
        "description": "400G QSFP-DD SR4",
        "comments": "Celestica qualified optic for DS4000/DS4001.",
        "attribute_data": {
            "cage_type": "QSFP-DD",
            "medium": "MMF",
            "connector": "MPO-12",
            "wavelength_nm": 850,
            "standard": "400GBASE-SR4",
            "reach_class": "SR",
            "lane_count": 4,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "SR4",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-98211-DR",
        "part_number": "R4113-98211-DR",
        "description": "400G QSFP-DD DR4",
        "comments": "Celestica qualified optic for DS4000/DS4001.",
        "attribute_data": {
            "cage_type": "QSFP-DD",
            "medium": "SMF",
            "connector": "MPO-12",
            "wavelength_nm": 1310,
            "standard": "400GBASE-DR4",
            "reach_class": "DR",
            "lane_count": 4,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "DR4",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-98111-ZB",
        "part_number": "R4113-98111-ZB",
        "description": "400G QSFP-DD ZR/ZR+ (bright)",
        "comments": "Celestica qualified optic for DS4000/DS4001.",
        "attribute_data": {
            "cage_type": "QSFP-DD",
            "medium": "SMF",
            "connector": "LC",
            "standard": "400G ZR/ZR+",
            "reach_class": "ZR",
            "lane_count": 4,
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "R4113-98111-ZR",
        "part_number": "R4113-98111-ZR",
        "description": "400G QSFP-DD ZR/ZR+",
        "comments": "Celestica qualified optic for DS4000/DS4001.",
        "attribute_data": {
            "cage_type": "QSFP-DD",
            "medium": "SMF",
            "connector": "LC",
            "standard": "400G ZR/ZR+",
            "reach_class": "ZR",
            "lane_count": 4,
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Generic",
        "manufacturer_slug": "generic",
        "model": "QSFP112-200GBASE-SR2",
        "part_number": "QSFP112-200GBASE-SR2",
        "description": "200G QSFP112 SR2 (MPO-12) — generic placeholder; replace with vendor SKU when qualified",
        "comments": (
            "Generic placeholder for the server-side QSFP112 host optic used in XOC-64 "
            "soc_storage_server_4x200 connections. The switch side uses Celestica R4113-A9220-VR "
            "(800G OSFP112 2xVR4) with an external Y-splitter. Replace this entry with a "
            "vendor-qualified SKU when the deployment optic is selected."
        ),
        "attribute_data": {
            "cage_type": "QSFP112",
            "medium": "MMF",
            "connector": "MPO-12",
            "wavelength_nm": 850,
            "standard": "200GBASE-SR2",
            "reach_class": "SR",
            "lane_count": 2,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "SR2",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "EPS Global",
        "manufacturer_slug": "eps-global",
        "model": "T1-QSFP112-200G-SR2",
        "part_number": "T1-QSFP112-200G-SR2",
        "description": "200G QSFP112 SR2 transceiver, MMF 2-channel MPO12, 850nm, 50m",
        "comments": "Qualified 200G QSFP112 SR2 optic for server-side 200GbE links.",
        "attribute_data": {
            "cage_type": "QSFP112",
            "medium": "MMF",
            "connector": "MPO-12",
            "wavelength_nm": 850,
            "standard": "200GBASE-SR2",
            "reach_class": "SR",
            "lane_count": 2,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "SR2",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "EPS Global",
        "manufacturer_slug": "eps-global",
        "model": "T1-OSFP112-400G-SR4",
        "part_number": "T1-OSFP112-400G-SR4",
        "description": "400G OSFP Multimode Flat top transceiver, 1xMPO12, 850nm, 50m",
        "comments": "Qualified 400G OSFP SR4 optic for server-side 400GbE links.",
        "attribute_data": {
            "cage_type": "OSFP",
            "medium": "MMF",
            "connector": "MPO-12",
            "wavelength_nm": 850,
            "standard": "400GBASE-SR4",
            "reach_class": "SR",
            "lane_count": 4,
            "host_serdes_gbps_per_lane": 100,
            "optical_lane_pattern": "SR4",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "EPS Global",
        "manufacturer_slug": "eps-global",
        "model": "T1-QSFP28-100G-SR4",
        "part_number": "T1-QSFP28-100G-SR4",
        "description": "100GBASE-SR4 QSFP28 850nm 100m DOM Transceiver Module",
        "comments": "Qualified 100G QSFP28 SR4 optic for server-side and DS3000-side 100GbE links.",
        "attribute_data": {
            "cage_type": "QSFP28",
            "medium": "MMF",
            "connector": "MPO-12",
            "wavelength_nm": 850,
            "standard": "100GBASE-SR4",
            "reach_class": "SR",
            "lane_count": 4,
            "host_serdes_gbps_per_lane": 25,
            "optical_lane_pattern": "SR4",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Generic",
        "manufacturer_slug": "generic",
        "model": "SFP28-25GBASE-SR",
        "part_number": "SFP28-25GBASE-SR",
        "description": "25G SFP28 SR optic (LC)",
        "comments": "Generic placeholder for symmetric 25GbE in-band management optics.",
        "attribute_data": {
            "cage_type": "SFP28",
            "medium": "MMF",
            "connector": "LC",
            "wavelength_nm": 850,
            "standard": "25GBASE-SR",
            "reach_class": "SR",
            "lane_count": 1,
            "host_serdes_gbps_per_lane": 25,
            "optical_lane_pattern": "SR",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "Celestica-SFP28-25GBASE-SR-PLACEHOLDER",
        "part_number": "Celestica-SFP28-25GBASE-SR-PLACEHOLDER",
        "description": "25G SFP28 SR optic (LC) — Celestica switch-side placeholder",
        "comments": (
            "Placeholder for Celestica-qualified 25GbE switch-side optics in compositions "
            "where switch optics must be vendor-branded while the exact SKU is still pending."
        ),
        "attribute_data": {
            "cage_type": "SFP28",
            "medium": "MMF",
            "connector": "LC",
            "wavelength_nm": 850,
            "standard": "25GBASE-SR",
            "reach_class": "SR",
            "lane_count": 1,
            "host_serdes_gbps_per_lane": 25,
            "optical_lane_pattern": "SR",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Generic",
        "manufacturer_slug": "generic",
        "model": "SFP+-10GBASE-SR",
        "part_number": "SFP+-10GBASE-SR",
        "description": "10G SFP+ SR optic (LC)",
        "comments": "Generic placeholder for symmetric 10GbE uplink optics.",
        "attribute_data": {
            "cage_type": "SFP+",
            "medium": "MMF",
            "connector": "LC",
            "wavelength_nm": 850,
            "standard": "10GBASE-SR",
            "reach_class": "SR",
            "lane_count": 1,
            "host_serdes_gbps_per_lane": 10,
            "optical_lane_pattern": "SR",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "Celestica-SFP+-10GBASE-SR-PLACEHOLDER",
        "part_number": "Celestica-SFP+-10GBASE-SR-PLACEHOLDER",
        "description": "10G SFP+ SR optic (LC) — Celestica switch-side placeholder",
        "comments": (
            "Placeholder for Celestica-qualified 10GbE switch-side optics in compositions "
            "where switch optics must be vendor-branded while the exact SKU is still pending."
        ),
        "attribute_data": {
            "cage_type": "SFP+",
            "medium": "MMF",
            "connector": "LC",
            "wavelength_nm": 850,
            "standard": "10GBASE-SR",
            "reach_class": "SR",
            "lane_count": 1,
            "host_serdes_gbps_per_lane": 10,
            "optical_lane_pattern": "SR",
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Generic",
        "manufacturer_slug": "generic",
        "model": "RJ45-1000BASE-T",
        "part_number": "RJ45-1000BASE-T",
        "description": "1G copper RJ45 transceiver/PHY placeholder",
        "comments": (
            "Generic placeholder for 1GbE copper management links where DIET "
            "must model a transceiver on both ends of the connection."
        ),
        "attribute_data": {
            "cage_type": "RJ45",
            "medium": "Copper",
            "connector": "RJ45",
            "standard": "1000BASE-T",
            "reach_class": "Copper",
            "lane_count": 1,
            "host_serdes_gbps_per_lane": 1,
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
    {
        "manufacturer": "Celestica",
        "manufacturer_slug": "celestica",
        "model": "Built-in-RJ45",
        "part_number": "Built-in-RJ45",
        "description": "Built-in/native RJ45 port placeholder — no removable transceiver required",
        "comments": (
            "Placeholder for a built-in Celestica switch RJ45 management port. "
            "This is not an external pluggable transceiver and should not be interpreted as a removable optic."
        ),
        "attribute_data": {
            "cage_type": "RJ45",
            "medium": "Copper",
            "connector": "RJ45",
            "standard": "1000BASE-T",
            "reach_class": "Copper",
            "lane_count": 1,
            "host_serdes_gbps_per_lane": 1,
            "gearbox_present": False,
            "cable_assembly_type": "none",
            "breakout_topology": "1x",
        },
    },
]


STATIC_NIC_MODULE_TYPES = [
    {
        "manufacturer": "Broadcom",
        "manufacturer_slug": "broadcom",
        "model": "BCM957508-P2100G",
        "part_number": "BCM957508-P2100G",
        "description": "Dual-port 100 Gb/s PCIe NIC",
        "comments": "Broadcom NetXtreme-E adapter.",
        "interface_templates": [
            ("port0", "100gbase-x-qsfp28"),
            ("port1", "100gbase-x-qsfp28"),
        ],
    },
    {
        "manufacturer": "Supermicro",
        "manufacturer_slug": "supermicro",
        "model": "AOC-CX766003N-SQ0",
        "part_number": "AOC-CX766003N-SQ0",
        "description": "1x NDR400G IB/EN OSFP Gen5 x16 CX7",
        "comments": "Supermicro / NVIDIA ConnectX-7 adapter.",
        "interface_templates": [("port0", "400gbase-x-osfp")],
    },
    {
        "manufacturer": "Supermicro",
        "manufacturer_slug": "supermicro",
        "model": "GPU-NVDPU-BA3220-C",
        "part_number": "GPU-NVDPU-BA3220-C",
        "description": "BlueField-3 BF3220 DPU 200GbE dual port Crypto Enable",
        "comments": "Supermicro BlueField-3 DPU.",
        "interface_templates": [
            ("port0", "200gbase-x-qsfp112"),
            ("port1", "200gbase-x-qsfp112"),
        ],
    },
    {
        "manufacturer": "Supermicro",
        "manufacturer_slug": "supermicro",
        "model": "AOC-CX7AH0078-DTZ",
        "part_number": "AOC-CX7AH0078-DTZ",
        "description": "2x200G EN/IB QSFP112 Gen5 x16 No Crypto CX7",
        "comments": "Supermicro / NVIDIA ConnectX-7 adapter.",
        "interface_templates": [
            ("port0", "200gbase-x-qsfp112"),
            ("port1", "200gbase-x-qsfp112"),
        ],
    },
    {
        "manufacturer": "Supermicro",
        "manufacturer_slug": "supermicro",
        "model": "AOC-AG-I4M-O",
        "part_number": "AOC-AG-I4M-O",
        "description": "AIOM G2.1 x4 4x 1GbE RJ45 Intel i350-AM4",
        "comments": "Supermicro AIOM Ethernet adapter.",
        "interface_templates": [
            ("port0", "1000base-t"),
            ("port1", "1000base-t"),
            ("port2", "1000base-t"),
            ("port3", "1000base-t"),
        ],
    },
    {
        "manufacturer": "Supermicro",
        "manufacturer_slug": "supermicro",
        "model": "AOC-AG-I2M-O",
        "part_number": "AOC-AG-I2M-O",
        "description": "AIOM G2.1 x4 2x 1GbE RJ45 Intel i350-AM2",
        "comments": "Supermicro AIOM Ethernet adapter.",
        "interface_templates": [
            ("port0", "1000base-t"),
            ("port1", "1000base-t"),
        ],
    },
    {
        "manufacturer": "Supermicro",
        "manufacturer_slug": "supermicro",
        "model": "AOC-CX7AH0079-DTZ",
        "part_number": "AOC-CX7AH0079-DTZ",
        "description": "2x200G ETH/IB QSFP112 Gen5 x16 Crypto CX7",
        "comments": "Supermicro / NVIDIA ConnectX-7 adapter.",
        "interface_templates": [
            ("port0", "200gbase-x-qsfp112"),
            ("port1", "200gbase-x-qsfp112"),
        ],
    },
    {
        "manufacturer": "Supermicro",
        "manufacturer_slug": "supermicro",
        "model": "AOC-ATG-i2TM-O",
        "part_number": "AOC-ATG-i2TM-O",
        "description": "AIOM 2-port 10GBase-T, Intel X550",
        "comments": "Supermicro AIOM Ethernet adapter.",
        "interface_templates": [
            ("port0", "10gbase-t"),
            ("port1", "10gbase-t"),
        ],
    },
    {
        "manufacturer": "Supermicro",
        "manufacturer_slug": "supermicro",
        "model": "AOC-S25G6-M2S-O",
        "part_number": "AOC-S25G6-M2S-O",
        "description": "Dual-port 25GbE SFP28 PCIe 4.0 x8 adapter",
        "comments": "Supermicro Ethernet adapter.",
        "interface_templates": [
            ("port0", "25gbase-x-sfp28"),
            ("port1", "25gbase-x-sfp28"),
        ],
    },
    {
        "manufacturer": "Supermicro",
        "manufacturer_slug": "supermicro",
        "model": "AOC-A100G-B2CM-O",
        "part_number": "AOC-A100G-B2CM-O",
        "description": "AIOM 2-port 100GbE QSFP28 based on Broadcom BCM57508",
        "comments": "Supermicro AIOM Ethernet adapter.",
        "interface_templates": [
            ("port0", "100gbase-x-qsfp28"),
            ("port1", "100gbase-x-qsfp28"),
        ],
    },
]

# Intentionally excluded from STATIC_NIC_MODULE_TYPES:
# - AOM-TPM-9672V-O: TPM module, not a network interface/transceiver.
