# Generated migration for NetBox Hedgehog plugin initial models

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0098_webhook_custom_field_data_webhook_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HedgehogFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(help_text='Unique name for this Hedgehog fabric', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this fabric')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('syncing', 'Syncing')], default='active', help_text='Current status of this fabric', max_length=20)),
                ('kubernetes_server', models.URLField(blank=True, help_text='Kubernetes API server URL (optional if using default kubeconfig)')),
                ('kubernetes_token', models.TextField(blank=True, help_text='Kubernetes service account token (leave empty to use kubeconfig)')),
                ('kubernetes_ca_cert', models.TextField(blank=True, help_text='Kubernetes CA certificate (leave empty to use kubeconfig)')),
                ('kubernetes_namespace', models.CharField(default='default', help_text="Default namespace for this fabric's CRDs", max_length=253)),
                ('sync_enabled', models.BooleanField(default=True, help_text='Enable automatic synchronization with Kubernetes')),
                ('sync_interval', models.PositiveIntegerField(default=300, help_text='Sync interval in seconds (0 to disable automatic sync)')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Timestamp of last successful sync', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message (if any)')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Hedgehog Fabric',
                'verbose_name_plural': 'Hedgehog Fabrics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(help_text='Kubernetes resource name (must be DNS-1123 compliant)', max_length=253)),
                ('namespace', models.CharField(default='default', help_text='Kubernetes namespace for this resource', max_length=253)),
                ('spec', models.JSONField(help_text='CRD specification as JSON')),
                ('labels', models.JSONField(blank=True, default=dict, help_text='Kubernetes labels as JSON')),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Kubernetes annotations as JSON')),
                ('kubernetes_status', models.CharField(choices=[('unknown', 'Unknown'), ('pending', 'Pending'), ('applied', 'Applied'), ('live', 'Live'), ('error', 'Error'), ('deleting', 'Deleting')], default='unknown', help_text='Current status in Kubernetes', max_length=20)),
                ('kubernetes_uid', models.CharField(blank=True, help_text='Kubernetes resource UID', max_length=36)),
                ('kubernetes_resource_version', models.CharField(blank=True, help_text='Kubernetes resource version', max_length=50)),
                ('last_applied', models.DateTimeField(blank=True, help_text='When this CRD was last applied to Kubernetes', null=True)),
                ('last_synced', models.DateTimeField(blank=True, help_text='When this CRD was last synced from Kubernetes', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message (if any)')),
                ('auto_sync', models.BooleanField(default=True, help_text='Enable automatic sync for this resource')),
                ('fabric', models.ForeignKey(help_text='Hedgehog fabric this CRD belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vpc_set', to='netbox_hedgehog.hedgehogfabric')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='extras.tag')),
            ],
            options={
                'verbose_name': 'VPC',
                'verbose_name_plural': 'VPCs',
                'ordering': ['fabric', 'namespace', 'name'],
                'unique_together': {('fabric', 'namespace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VPCPeering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(help_text='Kubernetes resource name (must be DNS-1123 compliant)', max_length=253)),
                ('namespace', models.CharField(default='default', help_text='Kubernetes namespace for this resource', max_length=253)),
                ('spec', models.JSONField(help_text='CRD specification as JSON')),
                ('labels', models.JSONField(blank=True, default=dict, help_text='Kubernetes labels as JSON')),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Kubernetes annotations as JSON')),
                ('kubernetes_status', models.CharField(choices=[('unknown', 'Unknown'), ('pending', 'Pending'), ('applied', 'Applied'), ('live', 'Live'), ('error', 'Error'), ('deleting', 'Deleting')], default='unknown', help_text='Current status in Kubernetes', max_length=20)),
                ('kubernetes_uid', models.CharField(blank=True, help_text='Kubernetes resource UID', max_length=36)),
                ('kubernetes_resource_version', models.CharField(blank=True, help_text='Kubernetes resource version', max_length=50)),
                ('last_applied', models.DateTimeField(blank=True, help_text='When this CRD was last applied to Kubernetes', null=True)),
                ('last_synced', models.DateTimeField(blank=True, help_text='When this CRD was last synced from Kubernetes', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message (if any)')),
                ('auto_sync', models.BooleanField(default=True, help_text='Enable automatic sync for this resource')),
                ('fabric', models.ForeignKey(help_text='Hedgehog fabric this CRD belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vpcpeering_set', to='netbox_hedgehog.hedgehogfabric')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='extras.tag')),
            ],
            options={
                'verbose_name': 'VPC Peering',
                'verbose_name_plural': 'VPC Peerings',
                'ordering': ['fabric', 'namespace', 'name'],
                'unique_together': {('fabric', 'namespace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VPCAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(help_text='Kubernetes resource name (must be DNS-1123 compliant)', max_length=253)),
                ('namespace', models.CharField(default='default', help_text='Kubernetes namespace for this resource', max_length=253)),
                ('spec', models.JSONField(help_text='CRD specification as JSON')),
                ('labels', models.JSONField(blank=True, default=dict, help_text='Kubernetes labels as JSON')),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Kubernetes annotations as JSON')),
                ('kubernetes_status', models.CharField(choices=[('unknown', 'Unknown'), ('pending', 'Pending'), ('applied', 'Applied'), ('live', 'Live'), ('error', 'Error'), ('deleting', 'Deleting')], default='unknown', help_text='Current status in Kubernetes', max_length=20)),
                ('kubernetes_uid', models.CharField(blank=True, help_text='Kubernetes resource UID', max_length=36)),
                ('kubernetes_resource_version', models.CharField(blank=True, help_text='Kubernetes resource version', max_length=50)),
                ('last_applied', models.DateTimeField(blank=True, help_text='When this CRD was last applied to Kubernetes', null=True)),
                ('last_synced', models.DateTimeField(blank=True, help_text='When this CRD was last synced from Kubernetes', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message (if any)')),
                ('auto_sync', models.BooleanField(default=True, help_text='Enable automatic sync for this resource')),
                ('fabric', models.ForeignKey(help_text='Hedgehog fabric this CRD belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vpcattachment_set', to='netbox_hedgehog.hedgehogfabric')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='extras.tag')),
            ],
            options={
                'verbose_name': 'VPC Attachment',
                'verbose_name_plural': 'VPC Attachments',
                'ordering': ['fabric', 'namespace', 'name'],
                'unique_together': {('fabric', 'namespace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VLANNamespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(help_text='Kubernetes resource name (must be DNS-1123 compliant)', max_length=253)),
                ('namespace', models.CharField(default='default', help_text='Kubernetes namespace for this resource', max_length=253)),
                ('spec', models.JSONField(help_text='CRD specification as JSON')),
                ('labels', models.JSONField(blank=True, default=dict, help_text='Kubernetes labels as JSON')),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Kubernetes annotations as JSON')),
                ('kubernetes_status', models.CharField(choices=[('unknown', 'Unknown'), ('pending', 'Pending'), ('applied', 'Applied'), ('live', 'Live'), ('error', 'Error'), ('deleting', 'Deleting')], default='unknown', help_text='Current status in Kubernetes', max_length=20)),
                ('kubernetes_uid', models.CharField(blank=True, help_text='Kubernetes resource UID', max_length=36)),
                ('kubernetes_resource_version', models.CharField(blank=True, help_text='Kubernetes resource version', max_length=50)),
                ('last_applied', models.DateTimeField(blank=True, help_text='When this CRD was last applied to Kubernetes', null=True)),
                ('last_synced', models.DateTimeField(blank=True, help_text='When this CRD was last synced from Kubernetes', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message (if any)')),
                ('auto_sync', models.BooleanField(default=True, help_text='Enable automatic sync for this resource')),
                ('fabric', models.ForeignKey(help_text='Hedgehog fabric this CRD belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vlannamespace_set', to='netbox_hedgehog.hedgehogfabric')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='extras.tag')),
            ],
            options={
                'verbose_name': 'VLAN Namespace',
                'verbose_name_plural': 'VLAN Namespaces',
                'ordering': ['fabric', 'namespace', 'name'],
                'unique_together': {('fabric', 'namespace', 'name')},
            },
        ),
    ]