# Generated by Django 5.2.9 on 2025-12-19 23:31

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_hedgehog', '0007_add_count_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='external',
            options={},
        ),
        migrations.AlterModelOptions(
            name='externalattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='externalpeering',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ipv4namespace',
            options={},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={},
        ),
        migrations.AlterModelOptions(
            name='switch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='switchgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vlannamespace',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vpc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vpcattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vpcpeering',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='external',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='externalattachment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='externalpeering',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ipv4namespace',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='switch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='switchgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vlannamespace',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vpc',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vpcattachment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vpcpeering',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='connection',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='connection',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='external',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='external',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='external',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='externalattachment',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='externalattachment',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='externalattachment',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='externalpeering',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='externalpeering',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='externalpeering',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='hedgehogfabric',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='hedgehogfabric',
            name='status',
            field=models.CharField(default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='hedgehogfabric',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='ipv4namespace',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='ipv4namespace',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='ipv4namespace',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='server',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='server',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='server',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='switch',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='switchgroup',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='switchgroup',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='switchgroup',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='vlannamespace',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='vlannamespace',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='vlannamespace',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='vpcattachment',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='vpcattachment',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='vpcattachment',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='vpcpeering',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='vpcpeering',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='netbox_hedgehog.hedgehogfabric'),
        ),
        migrations.AlterField(
            model_name='vpcpeering',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.CreateModel(
            name='BreakoutOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('breakout_id', models.CharField(max_length=50, unique=True)),
                ('from_speed', models.IntegerField()),
                ('logical_ports', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('logical_speed', models.IntegerField()),
                ('optic_type', models.CharField(blank=True, max_length=50)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Breakout Option',
                'verbose_name_plural': 'Breakout Options',
                'ordering': ['-from_speed', 'logical_ports'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NICModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('model_id', models.CharField(max_length=100, unique=True)),
                ('vendor', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('port_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('port_speed', models.IntegerField()),
                ('port_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'NIC Model',
                'verbose_name_plural': 'NIC Models',
                'ordering': ['vendor', 'model_id'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SwitchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('model_id', models.CharField(max_length=100, unique=True)),
                ('vendor', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('total_ports', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mclag_capable', models.BooleanField(default=False)),
                ('hedgehog_roles', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Switch Model',
                'verbose_name_plural': 'Switch Models',
                'ordering': ['vendor', 'model_id'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SwitchPortGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('group_name', models.CharField(max_length=100)),
                ('port_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('native_speed', models.IntegerField()),
                ('supported_breakouts', models.CharField(max_length=200)),
                ('port_range', models.CharField(max_length=50)),
                ('switch_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_groups', to='netbox_hedgehog.switchmodel')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Switch Port Group',
                'verbose_name_plural': 'Switch Port Groups',
                'ordering': ['switch_model', 'group_name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
