# Generated by Django 5.2.9 on 2025-12-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_hedgehog', '0010_devicetypeextension_fields'),
        ('netbox_hedgehog', '0013_seed_reference_data'),
    ]

    operations = [
    ]
