# Generated by Django 5.2.9 on 2025-12-22 22:34

from django.db import migrations


CUSTOM_FIELD_DEFINITIONS = [
    {
        'name': 'hedgehog_plan_id',
        'label': 'Hedgehog Plan ID',
        'type': 'text',
        'description': 'UUID of TopologyPlan that generated this object',
        'weight': 100,
        'content_types': [('dcim', 'device'), ('dcim', 'interface'), ('dcim', 'cable')],
    },
    {
        'name': 'hedgehog_class',
        'label': 'Hedgehog Class',
        'type': 'text',
        'description': 'Server or switch class ID',
        'weight': 101,
        'content_types': [('dcim', 'device')],
    },
    {
        'name': 'hedgehog_fabric',
        'label': 'Hedgehog Fabric',
        'type': 'text',
        'description': 'Fabric name for generated devices',
        'weight': 102,
        'content_types': [('dcim', 'device')],
    },
    {
        'name': 'hedgehog_role',
        'label': 'Hedgehog Role',
        'type': 'text',
        'description': 'Role for generated devices (server/leaf/spine)',
        'weight': 103,
        'content_types': [('dcim', 'device')],
    },
    {
        'name': 'hedgehog_zone',
        'label': 'Hedgehog Zone',
        'type': 'text',
        'description': 'Port zone name',
        'weight': 104,
        'content_types': [('dcim', 'interface')],
    },
    {
        'name': 'hedgehog_physical_port',
        'label': 'Hedgehog Physical Port',
        'type': 'integer',
        'description': 'Physical port number for breakout interfaces',
        'weight': 105,
        'content_types': [('dcim', 'interface')],
    },
    {
        'name': 'hedgehog_breakout_index',
        'label': 'Hedgehog Breakout Index',
        'type': 'integer',
        'description': 'Breakout lane index (1-based)',
        'weight': 106,
        'content_types': [('dcim', 'interface')],
    },
]


def create_custom_fields(apps, schema_editor):
    CustomField = apps.get_model('extras', 'CustomField')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Device = apps.get_model('dcim', 'Device')
    Interface = apps.get_model('dcim', 'Interface')
    Cable = apps.get_model('dcim', 'Cable')

    for definition in CUSTOM_FIELD_DEFINITIONS:
        content_type_map = {
            ('dcim', 'device'): ContentType.objects.get_for_model(Device),
            ('dcim', 'interface'): ContentType.objects.get_for_model(Interface),
            ('dcim', 'cable'): ContentType.objects.get_for_model(Cable),
        }
        content_types = [content_type_map[key] for key in definition['content_types']]

        custom_field, created = CustomField.objects.get_or_create(
            name=definition['name'],
            defaults={
                'label': definition['label'],
                'type': definition['type'],
                'description': definition['description'],
                'required': False,
                'weight': definition['weight'],
            },
        )

        custom_field.object_types.add(*content_types)



def remove_custom_fields(apps, schema_editor):
    CustomField = apps.get_model('extras', 'CustomField')
    CustomField.objects.filter(
        name__in=[field['name'] for field in CUSTOM_FIELD_DEFINITIONS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_hedgehog', '0014_merge_20251220_1746'),
    ]

    operations = [
        migrations.RunPython(create_custom_fields, remove_custom_fields),
    ]
