# Generated by Django 5.2.9 on 2025-12-22 22:50

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_hedgehog', '0015_add_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchPortZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('zone_name', models.CharField(help_text="Zone name (e.g., 'server-ports', 'spine-uplinks')", max_length=100)),
                ('zone_type', models.CharField(help_text='Port zone type', max_length=50)),
                ('port_spec', models.CharField(help_text="Port specification (e.g., '1-48', '1-32:2', '1,3,5')", max_length=200)),
                ('allocation_strategy', models.CharField(default='sequential', help_text='Port allocation strategy', max_length=50)),
                ('allocation_order', models.JSONField(blank=True, help_text='Explicit allocation order when using custom strategy', null=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower numbers allocate earlier', validators=[django.core.validators.MinValueValidator(1)])),
                ('breakout_option', models.ForeignKey(blank=True, help_text='Breakout option for logical ports (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='port_zones', to='netbox_hedgehog.breakoutoption')),
                ('switch_class', models.ForeignKey(help_text='Switch class this port zone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='port_zones', to='netbox_hedgehog.planswitchclass')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Switch Port Zone',
                'verbose_name_plural': 'Switch Port Zones',
                'ordering': ['switch_class', 'priority', 'zone_name'],
                'unique_together': {('switch_class', 'zone_name')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
