# Generated by Django 5.2.9 on 2025-12-23 01:08

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_hedgehog', '0016_switch_port_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('device_category', models.CharField(help_text='Device category this template applies to', max_length=50)),
                ('pattern', models.CharField(help_text="Python format string pattern (e.g., '{site}-{class}-{index:04d}')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of this naming template')),
                ('plan', models.ForeignKey(blank=True, help_text='Plan this template belongs to (null = global default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='naming_templates', to='netbox_hedgehog.topologyplan')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Naming Template',
                'verbose_name_plural': 'Naming Templates',
                'ordering': ['plan', 'device_category'],
                'unique_together': {('plan', 'device_category')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
