# Generated by Performance Engineering Specialist for enterprise-scale optimization

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('netbox_hedgehog', '0016_add_realtime_monitoring_fields'),
    ]

    operations = [
        # Fabric performance indexes
        migrations.RunSQL(
            sql=[
                # Fabric status and connection queries
                "CREATE INDEX IF NOT EXISTS idx_fabric_status_connection ON netbox_hedgehog_hedgehogfabric(status, connection_status);",
                "CREATE INDEX IF NOT EXISTS idx_fabric_sync_status ON netbox_hedgehog_hedgehogfabric(sync_status, last_sync);",
                "CREATE INDEX IF NOT EXISTS idx_fabric_active ON netbox_hedgehog_hedgehogfabric(status) WHERE status = 'active';",
                
                # Real-time monitoring indexes (only using existing fields)
                "CREATE INDEX IF NOT EXISTS idx_fabric_watch_enabled ON netbox_hedgehog_hedgehogfabric(watch_enabled);",
                "CREATE INDEX IF NOT EXISTS idx_fabric_watch_status ON netbox_hedgehog_hedgehogfabric(watch_status);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_fabric_status_connection;",
                "DROP INDEX IF EXISTS idx_fabric_sync_status;", 
                "DROP INDEX IF EXISTS idx_fabric_active;",
                "DROP INDEX IF EXISTS idx_fabric_watch_enabled;",
                "DROP INDEX IF EXISTS idx_fabric_watch_status;",
            ]
        ),
        
        # Add database constraints for performance
        migrations.RunSQL(
            sql=[
                # Ensure fabric names are unique for fast lookups
                "ALTER TABLE netbox_hedgehog_hedgehogfabric ADD CONSTRAINT unique_fabric_name UNIQUE (name);",
                
                # Add check constraints for status fields
                "ALTER TABLE netbox_hedgehog_hedgehogfabric ADD CONSTRAINT valid_status CHECK (status IN ('planned', 'active', 'maintenance', 'decommissioned'));",
                "ALTER TABLE netbox_hedgehog_hedgehogfabric ADD CONSTRAINT valid_connection_status CHECK (connection_status IN ('connected', 'disconnected', 'error', 'unknown'));",
                "ALTER TABLE netbox_hedgehog_hedgehogfabric ADD CONSTRAINT valid_sync_status CHECK (sync_status IN ('synced', 'syncing', 'error', 'never_synced'));",
            ],
            reverse_sql=[
                "ALTER TABLE netbox_hedgehog_hedgehogfabric DROP CONSTRAINT IF EXISTS unique_fabric_name;",
                "ALTER TABLE netbox_hedgehog_hedgehogfabric DROP CONSTRAINT IF EXISTS valid_status;",
                "ALTER TABLE netbox_hedgehog_hedgehogfabric DROP CONSTRAINT IF EXISTS valid_connection_status;",
                "ALTER TABLE netbox_hedgehog_hedgehogfabric DROP CONSTRAINT IF EXISTS valid_sync_status;",
            ]
        ),
        
        # Performance optimization for common queries
        migrations.RunSQL(
            sql=[
                # Partial indexes for active fabrics only (most common queries)
                "CREATE INDEX IF NOT EXISTS idx_active_fabric_git_url ON netbox_hedgehog_hedgehogfabric(git_repository_url) WHERE status = 'active' AND git_repository_url IS NOT NULL;",
                "CREATE INDEX IF NOT EXISTS idx_active_fabric_k8s_server ON netbox_hedgehog_hedgehogfabric(kubernetes_server) WHERE status = 'active' AND kubernetes_server IS NOT NULL;",
                
                # Covering index for fabric list queries
                "CREATE INDEX IF NOT EXISTS idx_fabric_list_covering ON netbox_hedgehog_hedgehogfabric(status, created, id) INCLUDE (name, description, connection_status, sync_status);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_active_fabric_git_url;",
                "DROP INDEX IF EXISTS idx_active_fabric_k8s_server;",
                "DROP INDEX IF EXISTS idx_fabric_list_covering;",
            ]
        ),
    ]