# Generated by Django 5.2.9 on 2025-12-23 05:46

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_hedgehog', '0017_naming_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When generation occurred')),
                ('device_count', models.IntegerField(help_text='Number of devices generated', validators=[django.core.validators.MinValueValidator(0)])),
                ('interface_count', models.IntegerField(help_text='Number of interfaces generated', validators=[django.core.validators.MinValueValidator(0)])),
                ('cable_count', models.IntegerField(help_text='Number of cables generated', validators=[django.core.validators.MinValueValidator(0)])),
                ('snapshot', models.JSONField(help_text='Plan state at generation time (for change detection)')),
                ('status', models.CharField(default='generated', help_text='Current generation status', max_length=50)),
                ('plan', models.OneToOneField(help_text='Topology plan this state belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='generation_state', to='netbox_hedgehog.topologyplan')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Generation State',
                'verbose_name_plural': 'Generation States',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
