# Generated by Django 5.2.9 on 2025-12-28 05:22

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_hedgehog', '0019_generationstate_to_plain_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planswitchclass',
            name='uplink_ports_per_switch',
            field=models.IntegerField(
                blank=True,
                help_text="Number of ports reserved for uplinks (explicit override). If not set, uplink capacity will be derived from SwitchPortZone with zone_type='uplink'. Either this field or uplink zones must be defined.",
                null=True,
                validators=[MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='devicetypeextension',
            name='uplink_ports',
            field=models.IntegerField(
                blank=True,
                help_text="[DEPRECATED] Number of ports reserved for uplinks. This field is unused in calculations. Use PlanSwitchClass.uplink_ports_per_switch or define SwitchPortZone with zone_type='uplink'. Will be removed in v2.0.",
                null=True,
                validators=[MinValueValidator(0)]
            ),
        ),
    ]
