# Generated by Django 4.2.x

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netbox_hedgehog', '0020_fix_gitrepository_created_by_field'),
    ]

    operations = [
        # Extend HedgehogResource model with bidirectional sync fields
        migrations.AddField(
            model_name='hedgehogresource',
            name='managed_file_path',
            field=models.CharField(
                max_length=500,
                blank=True,
                help_text="Path to managed file in GitOps repository"
            ),
        ),
        migrations.AddField(
            model_name='hedgehogresource',
            name='file_hash',
            field=models.CharField(
                max_length=64,
                blank=True,
                help_text="SHA-256 hash of current file content"
            ),
        ),
        migrations.AddField(
            model_name='hedgehogresource',
            name='last_file_sync',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text="Timestamp of last file synchronization"
            ),
        ),
        migrations.AddField(
            model_name='hedgehogresource',
            name='sync_direction',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('gui_to_git', 'GUI to Git'),
                    ('git_to_gui', 'Git to GUI'),
                    ('bidirectional', 'Bidirectional'),
                    ('disabled', 'Sync Disabled')
                ],
                default='bidirectional',
                help_text="Synchronization direction preference"
            ),
        ),
        migrations.AddField(
            model_name='hedgehogresource',
            name='conflict_status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('none', 'No Conflicts'),
                    ('detected', 'Conflict Detected'),
                    ('resolving', 'Resolution in Progress'),
                    ('resolved', 'Resolved')
                ],
                default='none',
                help_text="Current conflict status"
            ),
        ),
        migrations.AddField(
            model_name='hedgehogresource',
            name='conflict_details',
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text="Detailed conflict information"
            ),
        ),
        migrations.AddField(
            model_name='hedgehogresource',
            name='external_modifications',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="Log of external modifications detected"
            ),
        ),
        migrations.AddField(
            model_name='hedgehogresource',
            name='sync_metadata',
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text="Additional sync-related metadata"
            ),
        ),

        # Add GitRepository direct push capability
        migrations.AddField(
            model_name='gitrepository',
            name='direct_push_enabled',
            field=models.BooleanField(
                default=True,
                help_text="Enable direct push operations to this repository"
            ),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='push_branch',
            field=models.CharField(
                max_length=100,
                blank=True,
                help_text="Default branch for push operations (empty for default_branch)"
            ),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='commit_author_name',
            field=models.CharField(
                max_length=100,
                default='HNP Bidirectional Sync',
                help_text="Author name for automated commits"
            ),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='commit_author_email',
            field=models.EmailField(
                default='hnp-sync@hedgehog.gitops',
                help_text="Author email for automated commits"
            ),
        ),

        # Add HedgehogFabric directory status tracking
        migrations.AddField(
            model_name='hedgehogfabric',
            name='gitops_directory_status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('not_initialized', 'Not Initialized'),
                    ('initializing', 'Initializing'),
                    ('initialized', 'Initialized'),
                    ('error', 'Error'),
                    ('invalid_structure', 'Invalid Structure')
                ],
                default='not_initialized',
                help_text="Current GitOps directory structure status"
            ),
        ),
        migrations.AddField(
            model_name='hedgehogfabric',
            name='directory_init_error',
            field=models.TextField(
                blank=True,
                help_text="Last directory initialization error message"
            ),
        ),
        migrations.AddField(
            model_name='hedgehogfabric',
            name='last_directory_sync',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text="Timestamp of last directory synchronization"
            ),
        ),

        # Create SyncOperation model for tracking sync operations
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict)),
                ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='extras.tag')),
                ('fabric', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sync_operations',
                    to='netbox_hedgehog.hedgehogfabric'
                )),
                ('operation_type', models.CharField(
                    max_length=30,
                    choices=[
                        ('gui_to_github', 'GUI to GitHub'),
                        ('github_to_gui', 'GitHub to GUI'),
                        ('directory_init', 'Directory Initialization'),
                        ('conflict_resolution', 'Conflict Resolution'),
                        ('ingestion', 'File Ingestion')
                    ]
                )),
                ('status', models.CharField(
                    max_length=20,
                    choices=[
                        ('pending', 'Pending'),
                        ('in_progress', 'In Progress'),
                        ('completed', 'Completed'),
                        ('failed', 'Failed'),
                        ('cancelled', 'Cancelled')
                    ],
                    default='pending'
                )),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('details', models.JSONField(default=dict, blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('files_processed', models.PositiveIntegerField(default=0)),
                ('files_created', models.PositiveIntegerField(default=0)),
                ('files_updated', models.PositiveIntegerField(default=0)),
                ('files_deleted', models.PositiveIntegerField(default=0)),
                ('commit_sha', models.CharField(max_length=40, blank=True)),
                ('pull_request_url', models.URLField(blank=True)),
                ('initiated_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.SET_NULL,
                    null=True,
                    blank=True,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Sync Operation',
                'verbose_name_plural': 'Sync Operations',
                'ordering': ['-started_at'],
                'indexes': [
                    models.Index(fields=['fabric', 'status']),
                    models.Index(fields=['operation_type', 'status']),
                    models.Index(fields=['started_at']),
                    models.Index(fields=['fabric', 'operation_type', 'started_at']),
                ],
            },
        ),

        # Add indexes for performance optimization
        migrations.AddIndex(
            model_name='hedgehogresource',
            index=models.Index(fields=['fabric', 'managed_file_path'], name='hnp_resource_file_path_idx'),
        ),
        migrations.AddIndex(
            model_name='hedgehogresource',
            index=models.Index(fields=['conflict_status', 'last_file_sync'], name='hnp_resource_conflict_idx'),
        ),
        migrations.AddIndex(
            model_name='hedgehogresource',
            index=models.Index(fields=['sync_direction', 'fabric'], name='hnp_resource_sync_dir_idx'),
        ),
    ]