# Generated by Django 5.2.9 on 2026-01-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_hedgehog', '0025_add_boot_mac_custom_field'),
    ]

    operations = [
        # Add redundancy fields to PlanSwitchClass
        migrations.AddField(
            model_name='planswitchclass',
            name='groups',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of SwitchGroup names this switch belongs to. "
                          "Auto-populated from redundancy_group if not set. (e.g., ['mclag-1'])"
            ),
        ),
        migrations.AddField(
            model_name='planswitchclass',
            name='redundancy_type',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                choices=[
                    ('mclag', 'MCLAG - Multi-Chassis Link Aggregation'),
                    ('eslag', 'ESLAG - Enhanced Server Link Aggregation')
                ],
                help_text="Redundancy type for switches in this class. Leave blank for standalone switches."
            ),
        ),
        migrations.AddField(
            model_name='planswitchclass',
            name='redundancy_group',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                help_text="Redundancy group name (must match a SwitchGroup). Required if redundancy_type is set."
            ),
        ),
        # Add SwitchGroup fields to PlanMCLAGDomain
        migrations.AddField(
            model_name='planmclagdomain',
            name='switch_group_name',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                help_text="Name for generated SwitchGroup CRD (e.g., 'mclag-1', 'eslag-storage')"
            ),
        ),
        migrations.AddField(
            model_name='planmclagdomain',
            name='redundancy_type',
            field=models.CharField(
                max_length=50,
                default='mclag',
                choices=[
                    ('mclag', 'MCLAG'),
                    ('eslag', 'ESLAG')
                ],
                help_text="Redundancy type for this domain"
            ),
        ),
        # Update PlanMCLAGDomain meta options
        migrations.AlterModelOptions(
            name='planmclagdomain',
            options={
                'ordering': ['plan', 'switch_group_name'],
                'verbose_name': 'MCLAG Domain',
                'verbose_name_plural': 'MCLAG Domains'
            },
        ),
        migrations.AlterUniqueTogether(
            name='planmclagdomain',
            unique_together={('plan', 'switch_group_name')},
        ),
    ]
