# Generated by Django 5.2.9 on 2026-01-08 06:47

from django.db import migrations


def populate_switch_group_name(apps, schema_editor):
    """Populate switch_group_name from domain_id for existing records."""
    PlanMCLAGDomain = apps.get_model('netbox_hedgehog', 'PlanMCLAGDomain')
    for domain in PlanMCLAGDomain.objects.filter(switch_group_name__isnull=True):
        domain.switch_group_name = domain.domain_id
        domain.save(update_fields=['switch_group_name'])


def reverse_populate(apps, schema_editor):
    """Reverse data migration - set switch_group_name to None."""
    PlanMCLAGDomain = apps.get_model('netbox_hedgehog', 'PlanMCLAGDomain')
    PlanMCLAGDomain.objects.all().update(switch_group_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_hedgehog', '0026_add_redundancy_fields'),
    ]

    operations = [
        migrations.RunPython(populate_switch_group_name, reverse_populate),
    ]
