# Generated by Django 5.2.9 on 2026-01-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_hedgehog', '0027_populate_switch_group_name'),
    ]

    operations = [
        # Make switch_group_name non-nullable (all rows already populated by previous migration)
        migrations.AlterField(
            model_name='planmclagdomain',
            name='switch_group_name',
            field=models.CharField(
                max_length=100,
                help_text="Name for generated SwitchGroup CRD (e.g., 'mclag-1', 'eslag-storage')"
            ),
        ),
    ]
