# Generated by Django 5.2.9 on 2026-05-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_hedgehog', '0049_remove_osfp_interface_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakoutoption',
            name='optic_type',
        ),
    ]
