# Generated by Django 5.2.9 on 2026-05-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_hedgehog', '0051_remove_psc_legacy_flat_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Update Django's ORM state to match the removed field.
            state_operations=[
                migrations.RemoveField(
                    model_name='breakoutoption',
                    name='optic_type',
                ),
            ],
            # Use IF EXISTS so the migration is idempotent on dev DBs where
            # the column may have already been removed by a prior work-in-progress run.
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE netbox_hedgehog_breakoutoption DROP COLUMN IF EXISTS optic_type",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
