apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnoc-service-account
  namespace: cnoc
  labels:
    app: cnoc
    component: security
    security-policy: restricted
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cnoc
  name: cnoc-role
  labels:
    app: cnoc
    component: security
rules:
# ConfigMap permissions for CNOC configuration management
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "patch"]
  resourceNames: []
# Secret permissions for GitOps credentials (limited scope)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["cnoc-git-credentials", "cnoc-db-credentials"]
# Pod permissions for health checks and debugging
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
# Service permissions for internal communication
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
# Event permissions for logging and monitoring
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnoc-cluster-role
  labels:
    app: cnoc
    component: security
rules:
# CRD permissions for GitOps operations
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
# Network policy permissions for fabric management
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list"]
# Node permissions for cluster status monitoring
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
# Namespace permissions for multi-fabric operations
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
# Metrics permissions for monitoring
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnoc-role-binding
  namespace: cnoc
  labels:
    app: cnoc
    component: security
subjects:
- kind: ServiceAccount
  name: cnoc-service-account
  namespace: cnoc
roleRef:
  kind: Role
  name: cnoc-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnoc-cluster-role-binding
  labels:
    app: cnoc
    component: security
subjects:
- kind: ServiceAccount
  name: cnoc-service-account
  namespace: cnoc
roleRef:
  kind: ClusterRole
  name: cnoc-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cnoc-ingress-policy
  namespace: cnoc
  labels:
    app: cnoc
    component: security
spec:
  podSelector:
    matchLabels:
      app: cnoc
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8443
  # Allow ingress from monitoring (Prometheus)
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8080
  # Allow ingress from same namespace for inter-pod communication
  - from:
    - podSelector:
        matchLabels:
          app: cnoc
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 6379  # Redis
    - protocol: TCP
      port: 5432  # PostgreSQL
  egress:
  # Allow egress to Kubernetes API server
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
  # Allow egress to DNS
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow egress to database
  - to:
    - podSelector:
        matchLabels:
          app: postgresql
    ports:
    - protocol: TCP
      port: 5432
  # Allow egress to Redis
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  # Allow egress to external git repositories (GitOps)
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS
    - protocol: TCP
      port: 22   # SSH
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cnoc-default-deny
  namespace: cnoc
  labels:
    app: cnoc
    component: security
    policy: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  # No ingress or egress rules = deny all by default
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cnoc-security-policy
  labels:
    app: cnoc
    component: security
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true
  seLinux:
    rule: 'RunAsAny'
  seccompProfile:
    type: 'RuntimeDefault'
  forbiddenSysctls:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnoc-psp-role
  namespace: cnoc
  labels:
    app: cnoc
    component: security
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - cnoc-security-policy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnoc-psp-binding
  namespace: cnoc
  labels:
    app: cnoc
    component: security
roleRef:
  kind: Role
  name: cnoc-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cnoc-service-account
  namespace: cnoc
---
# Security Context Constraints (OpenShift compatibility)
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: cnoc-scc
  labels:
    app: cnoc
    component: security
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
allowedFlexVolumes: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1000
    max: 2000
priority: 10
readOnlyRootFilesystem: true
requiredDropCapabilities:
- ALL
runAsUser:
  type: MustRunAsNonRoot
  uidRangeMin: 1000
  uidRangeMax: 2000
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
  ranges:
  - min: 1000
    max: 2000
users:
- system:serviceaccount:cnoc:cnoc-service-account
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret